version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookstoredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"

  api:
    build: ./BookStore.API
    environment:
      ConnectionStrings__Default: "Host=127.0.0.1;Port=5432;Database=bookstoredb;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - db